name: release
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'skip ci') == false || contains(github.actor, 'bot') == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./
        if: contains(github.actor, 'bot') == false
        with:
          BOT_ID: ${{ vars.TALVIEW_BOT_ID }}
          BOT_KEY: ${{ secrets.TALVIEW_BOT_KEY }}
